import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/Header";
import { CartProvider } from "./context/CartContext";
import ConditionalContent from "./ConditionalContent";
import CartOnlyContent from "./CartOnlyContent";
import CheckoutOnlyContent from "./CheckoutOnlyContent";
import ConditionalFooter from "./ConditionalFooter";
import Braws from "./brows";
import Home from "./Card"; 
import Homee from "./Card/Topindex";
import Commentary from "./Comments";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <Header />

          <ConditionalContent>
            {children}
            <Home />
            <Homee />
            <Braws />
            <Commentary />
          </ConditionalContent>

          <CartOnlyContent />
          <CheckoutOnlyContent />
          <ConditionalFooter />
        </CartProvider>
      </body>
    </html>
  );
}
